version: "3.7"
services:
    minio:
        image: minio/minio:RELEASE.2021-06-07T21-40-51Z
        hostname: minio1
        volumes:
          - ./minio/data:/data
          - ./minio/.minio:/root/.minio
        ports:
          - 49154:9000
        environment:
          MINIO_ROOT_USER: minioadmin
          MINIO_ROOT_PASSWORD: minioadmin
        command: server /data
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3
        networks:
          - devel
    
    api:
        build: ./api
        #image: python:3.8-alpine 
        restart: always
        environment:
            # app
            - APP_PORT=49153
            # Minio
            - MINIO_HOST=minio:9000
            - ACCESS_KEY=minioadmin
            - SECRET_KEY=minioadmin
            - BUCKET_NAME=development
            # log path inside of container
            - LOG_PATH=/tmp
        volumes:
            # app
            - ./api:/usr/src/app
            # logs
            - /var/log/filemanager:/tmp
        networks:
            - devel
        ports:
            - 49153:49153
        depends_on:
            - minio
        command: /bin/ash -c "python app.py"

#    nginx:
#        image: nginx:1.19.2-alpine
#        hostname: nginx
#        volumes:
#            - ./nginx.conf:/etc/nginx/nginx.conf:ro
#        ports:
#            - "9000:9000"
#        depends_on:
#            - minio


networks:
  devel:
      external:
          name: devel